import typing as t

def f1(a: int) -> None: ...
def f2(a: str) -> None: ...
def f3(a: t.List[int]) -> None: ...
def f4(a: t.Dict[str, str]) -> None: ...
def f5(a: t.Iterable[str]) -> None: ...


def f10():
    x: int
    y: int = 0
    z: str
    w: str = 'Default w'

def f11(a: t.List[t.Union[int, float]]) -> None: ...

NumType = t.Union[str, float]
def f12(b: t.Dict[str, NumType]) -> None: ...


